### PR TITLE
Update btcde.py (self.nonce)

### PR DESCRIPTION
**Pull request by js931**
Avoid "invalid nonce" error for frequent API calls by raising the number by 1000.

**Edit: This doesn't help with parallel API calls on the same connection unfortunately... Only when creating new connections. Any idea on how to generate the nonce so that parallel calls don't pose a problem?**

### CODE REVIEW

**Comment by peshay** [comment]
- please do not change the version number, because the number of the version has nothing to do with the change you want to have
- I made an own branch for 2.3, please do your merge request to this branch
- I am not sure if this is really solving your issue, when opening a new connection the nonce is initially set and every time the API will be accessed, the nonce will be raised by +1. According to the API documentation the nonce should be always higher then the last nonce used. So my opinion is that within a use of the API connection the nonce should always +1 higher then before and I have no idea how parallel execution could work with that constraint, except you are 100% sure that the time on the systems you are using are exactly the same and instead of setting the nonce we could always use the current time based on nano seconds or something like this .. just an idea.

**Comment by js931** [comment]
Sorry, i'm new to Github... I added another change in the header nonce. Now it works fine for me, even with frequent parallel calls.

**Comment by peshay** [comment]
Finally build and test succeed. @js931 can you please test the latest changes here on your side, then I will make a new release for this change.

**Comment by js931** [comment]
Works fine for me, thanks! Only very rarely i am getting "invalid nonce" errors, but this isn't the fault of the btcde module, rather than my program. I guess one would have to implement a queue for parallel calls to get rid of those errors 100%.

**Pull request merged**
